app:
  port: 8080
database:
  url: postgres://dev:letmein@localhost/usrv_db
logging:
  filters: actix_server=info,actix_web=info,user_service=info
jwt:
  access_secret: super-secret-access
  access_exp_ms: 900000
  session_secret: super-secret-session
  session_exp_ms: 604800000
